'use client'
import {Roboto } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import Footer from "./_components/Footer";
import { ClerkProvider } from "@clerk/nextjs";
import { CartContext } from "./_context/context";
import { useState } from "react";
const geistSans = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  weight:"700"
});

const geistMono = Roboto({
  variable: "--font-geist-mono",
  subsets: ["latin"],
    weight:"700"
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [cart,setCart]=useState([])
  return (
    <ClerkProvider>
    <CartContext.Provider value={{cart,setCart}}>
        <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
    </CartContext.Provider>
    </ClerkProvider>

  );
}
